name: Daily Commit

on:
  schedule:
    - cron: "0 10 * * *"   # 10:00 UTC daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make daily update
        run: |
          echo "Update on $(date -u)" >> log.md

      - name: Commit changes
        run: |
          git config user.email "anjalipandey2124@gmail.com"
          git config user.name "anjalipandey21"
          git add log.md
          git commit -m "chore: daily update" || echo "Nothing to commit"
          git push
